### ISSUE TITLE
Implementação de funcao Back

### ISSUE THREAD

**Issue by jose-varela** [bittencourtthulio/Router4Delphi#1]
Senti a necessidade de poder controlar a lista do History para poder implementar um botão Back num app, ou seja poder chamar a rota anterior da atual. Thulio solicitou que abrisse uma issue.
Decidi arriscar a fazer as alteraçoes e estão funcionando, gostaria poder contribuir com o projeto se é possível, não consegui fazer um pull request.
Fiz uma analise das possíveis soluções e acabei criando uma lista FLIstCacheOrder: TList<String>que é preenchida por um evento OnKeyNotify disparado toda vez que uma Key da FListCache é adicionada ou eliminada.
Aproveitei também e criei uma function BreadCrumb que nos retorna a lista das rotas anteriores a atual.
Não sei se a solução implementada seja a melhor opção, caso achem interessante posso disponibilizar.

procedure TRouter4DHistory.CacheKeyNotify(Sender: TObject; const Key: string; Action: TCollectionNotification);
begin
     inherited;

     case Action of
       cnAdded:
       begin
          Self.FListCacheOrder.Add(Key);
          Self.FIndexCache := Self.FListCacheOrder.Count-1;
       end;

       cnRemoved:
       begin
          Self.FListCacheOrder.Remove(Key);
          Self.FIndexCache := Self.FListCacheOrder.Count-1;
       end;
     end;
end;

function TRouter4DHistory.GoBack: string;
begin
     if Self.FIndexCache > 0 then
        Dec(Self.FIndexCache);

     Result := Self.FListCacheOrder[Self.FIndexCache];
end;

function TRouter4DHistory.BreadCrumb(ADelimiter: char = '/'): string;
var i : integer;
begin
     Result := '';

     if Self.FIndexCache = -1 then
        Exit;

     Result := Self.FListCacheOrder[Self.FIndexCache];

     for i := Self.FIndexCache-1 downto 0 do
     begin
        Result := Self.FListCacheOrder[i] + ADelimiter + Result;
     end;
end;

function TRouter4DHistory.IndexCache: integer;
begin
     Result := Self.FIndexCache;
end;

**Comment by alepmedeiros** [comment]
implementado a solicitação
