### ISSUE TITLE
Erro ao compilar em 64bits Delphi 12

### ISSUE THREAD

**Issue by JFSF** [bittencourtthulio/Router4Delphi#18]
Não é possível compilar correctamente no Delphi 12 em 64 bits dado a uma incompatibilidade:

![image](https://github.com/academiadocodigo/Router4Delphi/assets/1583154/31033fce-5daf-4977-890c-4d084f7e22d2)

O mesmo problema não ocorre em 32 bits:

![image](https://github.com/academiadocodigo/Router4Delphi/assets/1583154/5a559a3f-43c0-4358-9793-4eb37e24dc75)

A solução passa por aqui:

![image](https://github.com/academiadocodigo/Router4Delphi/assets/1583154/eaf47330-4c99-40a3-9326-c96eef93cae8)

**Comment by adrianosantostreina** [comment]
Fixed in the latest version.
