### ISSUE TITLE
Problema com Router4D

### ISSUE THREAD

**Issue by itamarso** [bittencourtthulio/Router4Delphi#2]
[dcc32 Error] DelphiUP.View.Layouts.Principal.pas(11): E2291 Missing implementation of interface method iRouter4DComponent.Render
Problema detectado apartir da versão 1.0.3 e 1.0.4 ao configurar TPrimeiraTela = class(TForm, iRouter4DComponent) o delphi não compilar fiz o downgrede para a versão 1.0.2 está funcionando perfeitamente.

**Comment by bittencourtthulio** [comment]
A partir da versão 1.0.3 foi implementado suporte para VCL, com isso foi adicionado no projeto o arquivo Router4D.inc se seu projeto foi VCL comente com "//" a diretiva HAS_FMX caso contrario deixe a diretiva descomentada.

Essa informações está disponivel dentro da documentação do Router4D no Readme aqui no Github, sempre leia a documentação quando tiver uma atualização do projeto, especificamos lá todos os detalhes.

**Comment by itamarso** [comment]
FireMonkey

**Comment by itamarso** [comment]
Resolvido. Obrigado
