### ISSUE TITLE
Erro na Compilação Delphi 12.1 64-bit

### ISSUE THREAD

**Issue by isaqueribeiro** [bittencourtthulio/Router4Delphi#20]
O componente não está compilação em 64 bits, na versão Delphi 12.1

Erro : 
**[dcc64 Error] ObjectsMappers.pas(1183): E2251 Ambiguous overloaded call to 'Create'
System.JSON.pas(465): Related method: constructor TJSONNumber.Create(const Currency);
System.JSON.pas(461): Related method: constructor TJSONNumber.Create(const Extended);**

![image](https://github.com/academiadocodigo/Router4Delphi/assets/10811863/17dc2cd7-967a-4c4c-bdee-237eb17d38e6)

**Comment by adrianosantostreina** [comment]
Fixed in the latest version.
