### ISSUE TITLE
Erro depois que atualizei

### ISSUE THREAD

**Issue by ageu** [bittencourtthulio/Router4Delphi#4]
Atualizei o minha versão agora pouco e estou obtendo o seguinte erro:
[dcc32 Error] view.base.pas(16): E2291 Missing implementation of interface method iRouter4DComponent.Render
Os dois metodos estão implementados, pois já estavam funcionando da versão anterior.
O que posso fazer para corrigir?

**Comment by ageu** [comment]
Era o arquivo Router4D.inc
uma diretiva de compilação estava para VCL e meu projeto é FMX

**Comment by L1NDS0N** [comment]
o que fez para corrigir o erro? qual o arquivo especificamente? eu tentei remover as diretivas na interface mas ela gera um efeito cascata de erros
