### ISSUE TITLE
HardwareBack no mobile

### ISSUE THREAD

**Issue by mauriciovictor** [bittencourtthulio/Router4Delphi#6]
Estou tentando tratar quando o usuário clica no botão de voltar ir fazendo a navegação, mas o aplicativo fecha, já tentei configurar no onKeyUp do form porém o aplicativo fecha de qualquer forma, tem como fazer com o aplicativo volte pra ultima tela sem fechar o app?

**Comment by adrianosantostreina** [comment]
Maurício, tudo bem?
Tem sim, mas não é responsabilidade o Router4D fazer isso, até porque não temos como saber para onde voltar. Se tratarmos somente os forms, ok, sem problemas. Mas o HardwareBack tem mais funções, exemplo: Se você tem uma Popup aberta, o correto é o HardwareBack fechar o popup. Se o usuário está em uma janela que tem abas, o HardwareBack pode voltar aba por aba, portanto é muito mais complexo. 

Cada programador precisa fazer seus próprios ajustes. 
Recomendo que você crie uma função geral no OnKeyUp do form principal e em cada form adjacente, crie um mecanismo próprio de retorno para atender outras funções do HardwareBack.
