### ISSUE TITLE
Consider using English in in documentation and library introduction

### ISSUE THREAD

**Issue by TommiPrami** [bittencourtthulio/Router4Delphi#8]
Just my 0.02€, your project, you are the boss. Sounds interesting, but hard to figure out what it does and whats features it has.

-Tee-

**Comment by alepmedeiros** [comment]
hello my friend, I have this English translation in my backlog

**Comment by adrianosantostreina** [comment]
The translation has been done. At the end of the documentation there is a link to the English documentation.
